name: Create pull request checks

on:
  pull_request:
    types: [synchronize, opened]
    branches:
      - main
jobs:
  add_checks:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Add checks
        uses: actions/github-script@v7
        with:
          script: |
            const sha = "${{ github.event.pull_request.head.sha }}";

            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Unit Test',
              head_sha: sha,
              actions: [
                {
                  label: 'Unit Test',
                  description: 'Run unit test',
                  identifier: 'unit-test'
                }
              ]
            })
            
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Lint Project',
              head_sha: sha,
              actions: [
                {
                  label: 'Lint Project',
                  description: 'Run eslint to fix the project.',
                  identifier: 'lint'
                }
              ]
            })
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
