on:
  issue_comment:
    types: [ created ]


jobs:
  running_ci:
    name: Run CI.
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run-ci' }}
    permissions:
      issues: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Do CI
        id: ci_result
        run: |
          echo "changed=1" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.pr_branch.outputs.result }}
    outputs:
      changed: ${{ job.running_ci.stpes.ci_result.changed }}
  test:
    name: 'Run unit test'
    runs-on: ubuntu-latest
    needs: running_ci
    steps:
      - name: echo
        run: echo $CHANGED && echo $env
        env:
          CHANGED: ${{ need.running_ci.outputs.changed }}
