on:
  issue_comment:
    types: [ created ]


jobs:
  running_ci:
    name: Run CI.
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run-ci' }}
    permissions:
      issues: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Do CI
        id: ci_result
        run: |
          echo "nothing"
      - name: echo
        run: echo $CHANGED && echo "hello??"
        env:
          CHANGED: ${{ steps.ci_result.outputs.changed }}

    outputs:
      changed: ${{ steps.ci_result.outputs.changed }}
  test:
    name: 'Run unit test'
    runs-on: ubuntu-latest
    if: ${{ needs.running_ci.outputs.changed == 0 }}
    needs: running_ci
    steps:
      - name: echo
        run: echo $CHANGED && env
        env:
          CHANGED: ${{ needs.running_ci.outputs.changed }}
