on:
  issue_comment:
    types: [ created ]


jobs:
  running_ci:
    name: Run CI.
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run-ci' }}
    permissions:
      issues: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: nextjs-particlex-theme/sitemap-generate@75b6b1fc1ba92d4e444e813a3725aa11f511eaab
        with:
          who-to-greet: 'Mona the Octocat'



    outputs:
      changed: ${{ steps.ci_result.outputs.changed }}
  test:
    name: 'Run unit test'
    runs-on: ubuntu-latest
    if: ${{ needs.running_ci.outputs.changed == 0 }}
    needs: running_ci
    steps:
      - name: echo
        run: echo $CHANGED && env
        env:
          CHANGED: ${{ needs.running_ci.outputs.changed }}
