on:
  issue_comment:
    types: [created]
jobs:
  running_ci:
    name: Lint project and test.
    if: ${{ github.event.comment.body == '/run-ci' }}
    runs-on: ubuntu-latest
    steps:
     - run: echo "You just called $"
       env:
         NUMBER: ${{ github.event.comment.body }}
